### ISSUE TITLE
CharacterSync doesn't work with 6.1 update

### ISSUE THREAD

**Issue by DorkmasterFlek** [goaaats/Dalamud.CharacterSync#12]
Plugin is outdated after the Dalamud 6.1 update.

**Comment by LukasArevalo** [comment]
Can we expect an update soon? There doesn't look to be any  updates since December last year..

**Comment by yxshx** [comment]
really liked this plugin, I hope they update it for 6.1

**Comment by ZyphiraZircon** [comment]
created a pull request, it should be as routine of a fix as updating the dalamud packager inclusion version number, I know I make frequent use of this plugin too so I'd like to use it again ASAP lmao

**Comment by Werns** [comment]
This was not fixed by PR #14

**Comment by AetherCollective** [comment]
Workaround: https://github.com/goaaats/Dalamud.CharacterSync/pull/14#issuecomment-1115475221
