### ISSUE TITLE
Character Sync has disappeared from the list of available plugins

### ISSUE THREAD

**Issue by CharlieDelune** [goaaats/Dalamud.CharacterSync#7]
I don't seem to be able to find the Character Sync plugin in the list of dalamud plugins anymore. I've tried to manually add this repo a hundred different ways, but none of them work. I have a few friends who are also unable to see it.

**Comment by goaaats** [comment]
Hey, there's some technical problems with this plugin atm that keep it from working correctly. We hope to be able to restore it after the expansion releases.

**Comment by CharlieDelune** [comment]
Quick reply, thanks! Worth noting it had been working fine for me... I now regret disabling it to try and help my friend figure out the issue
